services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:17
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Saturn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  saturn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_CONNECTION_URL=postgres://admin:password@postgresql:5432/Saturn
      - REDIS_CONNECTION_URL=redis://redis:6379
      - SCHEDULER_COUNT=1
      - WORKER_COUNT=1
      - FAULT_TOLERANCE_COUNT=1
    depends_on:
      - redis
      - postgresql

volumes:
  postgres_data:
