services:
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:17
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Saturn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  saturn-api:
    build: .
    command: ["./saturn", "api"]
    expose:
      - "8000"
    environment:
      - POSTGRES_CONNECTION_URL=postgres://admin:password@postgresql:5432/Saturn
      - REDIS_CONNECTION_URL=redis://redis:6379
    depends_on:
      - redis
      - postgresql
      - saturn-migrations

  saturn-scheduler:
    build: .
    command: ["./saturn", "scheduler"]
    expose:
      - "8000"
    environment:
      - POSTGRES_CONNECTION_URL=postgres://admin:password@postgresql:5432/Saturn
      - REDIS_CONNECTION_URL=redis://redis:6379
    depends_on:
      - redis
      - postgresql
      - saturn-migrations

  saturn-worker:
    build: .
    command: ["./saturn", "worker"]
    expose:
      - "8000"
    environment:
      - POSTGRES_CONNECTION_URL=postgres://admin:password@postgresql:5432/Saturn
      - REDIS_CONNECTION_URL=redis://redis:6379
    depends_on:
      - redis
      - postgresql
      - saturn-migrations

  saturn-migrations:
    build: .
    command: ["./saturn", "migration"]
    depends_on:
      - postgresql
    restart: "no"
    environment:
      - POSTGRES_CONNECTION_URL=postgres://admin:password@postgresql:5432/Saturn
      - REDIS_CONNECTION_URL=redis://redis:6379

  saturn-fault-tolerance:
    build: .
    command: ["./saturn", "fault-tolerance"]
    depends_on: 
      - postgresql
      - redis
    environment:
      - POSTGRES_CONNECTION_URL=postgres://admin:password@postgresql:5432/Saturn
      - REDIS_CONNECTION_URL=redis://redis:6379

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - saturn-api
      - saturn-scheduler
      - saturn-worker

  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  nginx:
    image: nginx:latest
    ports: 
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - saturn-api

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
